### ISSUE TITLE
Docker progress

### ISSUE THREAD

**Issue by doublemarked** [serverless/serverless-python-requirements#112]
Just getting things set up, `serverless package` was hanging every time after the following line:

```
Serverless: Docker Image: lambci/lambda:build-python3.6
```

I poked around and determined that it's just taking a quite long time (~15min) to pull the docker images. That's fine, but it was quite unclear at first. It would help to have some details on the command line, either a progress meter or at least a warning.

**Comment by cgrimal** [comment]
See function `ensureImage` of the [serverless-package-python-functions](https://github.com/ubaniabalogun/serverless-package-python-functions/) plugin.

They are using a `docker images ...` command to check if the image is already here or not, in order to display a warning message.

We could do the same I guess?

**Comment by dschep** [comment]
That's a good idea @cgrimal

**Comment by dfee** [comment]
I'm glad I saw this. I'm manually pulling the images so I can watch the progress bar. Would be helpful if STDOUT was passed through...

**Comment by pgrzesik** [comment]
Hey 👋 I'm closing this ticket as it looks like it's heavily outdated, we can of course reopen it if needed 👍
