### ISSUE TITLE
Serverless.yml settings for Django App

### ISSUE THREAD

**Issue by ptrhck** [serverless/serverless-python-requirements#199]
Hi,

I would like to directly point to https://github.com/logandk/serverless-wsgi/issues/62. Any ideas what the problem might be? Moreover, I am aware of the sqlite issue regarding the python linux installation on AWS lambda. Is there a solution to this within this plugin? Zappa is having this feature as far as I can tell.

Cheers

**Comment by dschep** [comment]
What does your requirements.txt contain? And you're trying to deploy a django project? That's really odd that the error is about werkzeug, since AFAIK django doesn't use that.

And I see the sqlite error. I'm not familiar with that issue, do you have documentation about it? It's really disappointing that AWS would ship an incomplete standard library.

**Comment by chrisstetter** [comment]
[Here ](https://stackoverflow.com/questions/44058239/sqlite3-error-on-aws-lambda-with-python-3) it is stated that the package is missing in AWS Lambda. An the [lambda-packages](https://github.com/Miserlou/lambda-packages) provide most of the when deploying with Zappa.

Well, I have installed the werkzeug package as it was required by the https://github.com/logandk/serverless-wsgi package when starting the app offline `with sls wsgi serve`.

Regarding the requirements.txt:

```
aniso8601==3.0.0
Django==2.0.6
graphene==2.1.1
graphene-django==2.0.0
graphql-core==2.0
graphql-relay==0.4.5
iso8601==0.1.12
promise==2.1
pytz==2018.4
Rx==1.6.1
singledispatch==3.4.0.3
six==1.11.0
typing==3.6.4
Werkzeug==0.14.1
```

**Comment by dschep** [comment]
Hmm. What's using werkzeug? or does django now depend on that too?

For sqlite.. I'd mostly ignored zappa's lambda-packages integration because they're mostly packages from PyPi which work fine on lambda automatically with this plugin due to the docker integration. I didn't realize that sqlite is broken in AWS. As a workaround, you could probably use the [vendor](https://github.com/UnitedIncome/serverless-python-requirements#vendor-library-directory) option with the `_sqlite.so` file contained in [the lambda-packages version of sqlite](https://github.com/Miserlou/lambda-packages/raw/master/lambda_packages/sqlite3/python3.6-sqlite3-3.6.0.tar.gz)

**Comment by chrisstetter** [comment]
As mentioned above, https://github.com/logandk/serverless-wsgi requires werkzeug whereas neither django nor graphene-django does. So, there seems to be some issue with packaging of werkzeug while deploying a django app? Flask seems to be fine

**Comment by pgrzesik** [comment]
Hey 👋 I'm closing this ticket as it looks like it's heavily outdated, we can of course reopen it if needed 👍
