### ISSUE TITLE
security changes to bitbucket pipelines break dockerizePip

### ISSUE THREAD

**Issue by guyc** [serverless/serverless-python-requirements#201]
This is not a bug, but it may be helpful for others using this plugin within bitbucket pipelines.

Due to a change in bitbucket's security environment, this plugin started failing today on bitbucket pipelines with the following error
```
docker: Error response from daemon: authorization denied by plugin pipelines: -v only supports $BITBUCKET_CLONE_DIR.
```
BITBUCKET_CLONE_DIR is the checkout point of your repo in the pipeline.
Prior to today, bitbucket allowed `docker run -v` with subpaths of the clone dir.
This plugin will now fail to run in a pipeline unless it is at the root of the repository.

```
We have a change implemented earlier today which disabled sub directory mounts due to security reasons. This is why you are experiencing this error.

As mentioned by the error that -v only supports “BITBUCKET_CLONE_DIR“.

To proceed with mounting, you can use the “BITBUCKET_CLONE_DIR“ and navigate (cd to the directory) downward to the directory or file what you want to access.
```

**Comment by dschep** [comment]
Thanks for the report! I'll leave this open for a while since the change to bitbucket is new and others might be coming here to figure out what's wrong.

I assume bitbucket pipelines are run on 64 bit Linux machines. If that's the case and all the binary dependencies you need are available as many-linux wheels, you can leverage the [`non-linux` parameter for `dockerizePip`](https://github.com/UnitedIncome/serverless-python-requirements#cross-compiling) to avoid using docker in CI.

**Comment by guyc** [comment]
I did not know about that option.  That's perfect.  Thanks.

**Comment by pgrzesik** [comment]
Hey 👋 I'm closing this ticket as it looks like it's heavily outdated, we can of course reopen it if needed 👍
