### ISSUE TITLE
some questions about per-function requirements modules

### ISSUE THREAD

**Issue by amitm02** [serverless/serverless-python-requirements#207]
1) if functions in the different module needs a shared py file, how can they import it?
2) do files stated in the serverless.yml 
```
package:
 - include
```
are added to the lambdas?

**Comment by dschep** [comment]
correct.

**Comment by cgrimal** [comment]
Hi guys, have you successfully used it?
I have the same use case, and I can't make it work. The include/exclude directives are totally ignored, whether they are at the package top level, or at function level.

Please note I am using individually packaging.

**Comment by infinitedreams9586** [comment]
> Hi guys, have you successfully used it?
> I have the same use case, and I can't make it work. The include/exclude directives are totally ignored, whether they are at the package top level, or at function level.
> 
> Please note I am using individually packaging.

I have same issue. I mentioned the folder name in include but it is ignored.

**Comment by koushinrin** [comment]
Including files outside the module doesn't work.
It correctly packaged locally, but didn't deploy all the packaged files to the remote lambda.

**Comment by dschep** [comment]
if you have shared code outside the modules, symlink that into the modules.

**Comment by bweigel** [comment]
It seems like the `packaging` `include`s and `exclude`s won't have an impact on packaging if invoked with `individually: true`. This is due to the two part process underlying the implementation:

1) the basic serverless packaging creates a zip-File called `<functionname>.zip`, which basically contains (on a function level) everything according to the defined excludes and includes.
2) _a part of the zip-File_ resulting from step **1** is injected into a final zip (which also contains the requirements)

What do I mean, by _a part_? Only files contained under the directory specified by `module` are copied to the final zip.

see `inject.js`:
```javascript
function moveModuleUp(source, target, module, options) {
    ...
    .then(sourceZip => sourceZip.filter(file => file.startsWith(module + '/')))
    ...
```

**Comment by pgrzesik** [comment]
Hey 👋 I'm closing this ticket as it looks like it's heavily outdated, we can of course reopen it if needed 👍
