### ISSUE TITLE
Slim packages by using cache

### ISSUE THREAD

**Issue by kennydude** [serverless/serverless-python-requirements#260]
Would it be possible to slim packages by only keeping the Python bytecode?

Mapbox have seemingly been able to come up with some commands to move the pyc files into place so they are used instead of the py files (we can't really edit the source python files once it's on lambda anyway) -- https://blog.mapbox.com/aws-lambda-python-magic-e0f6a407ffc6 see "Magic trick"

**Comment by dschep** [comment]
Intereseting idea. But as they meniont, its a very small differenc compared to the .py files. It might make it a bit faster too tho. Currently, since it doesn't require a trick (moving files around) the slim option deletes the pyc files instead. 

It'd be interesting to do the otherway around as mapbox is doing, but that'll be a bit more complicated.

But also..  I didn't realize this. this is good to know: 
> LD_LIBRARY_PATH is set to /var/task/lib

**Comment by Suor** [comment]
Deleting pyc files makes cold start slower. I would leave them as is.

**Comment by dschep** [comment]
I don't remember the exact portability of pyc files. Namely, can a python3.6 pyc file from windows or mac os be used with python3.6 in linux?

**Comment by kennydude** [comment]
Linked from the original post [this post](http://www.network-theory.co.uk/docs/pytut/CompiledPythonfiles.html) suggests:

> The contents of the ‘spam.pyc’ file are platform independent, so a Python module directory can be shared by machines of different architectures.

**Comment by bweigel** [comment]
Maybe #276 could solve this. You could exclude `.py` files and override the deletion of the `.pyc` files.

**Comment by pgrzesik** [comment]
Hey 👋 I'm closing this ticket as it looks like it's heavily outdated, we can of course reopen it if needed 👍
